### ISSUE TITLE
请问目前能够解密并保存收到的图片吗

### ISSUE THREAD

**Issue by Ai-Yolo** [JustUndertaker/ntchat-client#1]
您好 请问ntchat-client 这个项目配置的文件缓存地址是怎么用呀，试了试收发图片 没有图片保存到目录呢

**Comment by JustUndertaker** [comment]
> 您好 请问ntchat-client 这个项目配置的文件缓存地址是怎么用呀，试了试收发图片 没有图片保存到目录呢

缓存地址是指client收到图片后（http，base64）会先将图片保存到缓存文件夹下，然后使用ntchat的接口发送出去，对于收到的图片，还是dat文件并没有进行解密。

**Comment by Ai-Yolo** [comment]
感谢！那后续会支持图片解密么？

**Comment by JustUndertaker** [comment]
> 感谢！那后续会支持图片解密么？

看了一下，微信的dat文件加密就是简单的异或加密，后面可以考虑做一下解密。

**Comment by JustUndertaker** [comment]
> > 感谢！那后续会支持图片解密么？
> 
> 看了一下，微信的dat文件加密就是简单的异或加密，后面可以考虑做一下解密。

已添加[图片解密](https://github.com/JustUndertaker/ntchat-client/commit/62de19db1491f65d9f7a5bea1a1a65ce485062f5)
