### ISSUE TITLE
拍一拍日志报错

### ISSUE THREAD

**Issue by Ai-Yolo** [JustUndertaker/ntchat-client#2]
问题描述：Http调用拍一拍接口，能正常收到拍一拍请求，但是日志有报错
问题截图：
![image](https://user-images.githubusercontent.com/11790369/197934209-c0cb8879-0c09-4ea1-9419-36783b5fc8c5.png)

**Comment by Ai-Yolo** [comment]
添加群成员为好友 文档参数错了，备注的参数应该是 verify 不是 remark [https://github.com/JustUndertaker/ntchat-client#%E6%B7%BB%E5%8A%A0%E7%BE%A4%E6%88%90%E5%91%98%E4%B8%BA%E5%A5%BD%E5%8F%8B](url)
<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">添加群成员为好友</h3><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">api地址：/add_room_friend</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">参数：</p>

字段名 | 数据类型 | 可选 | 默认值 | 说明
-- | -- | -- | -- | --
room_wxid | str | 必填 | None | 房间号
wxid | str | 必填 | None | 请求对方wxid
verify | str | 选填 | None | 备注

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">响应数据类型：None</p>
</body>
</html>

**Comment by JustUndertaker** [comment]
> 问题描述：Http调用拍一拍接口，能正常收到拍一拍请求，但是日志有报错 问题截图： ![image](https://user-images.githubusercontent.com/11790369/197934209-c0cb8879-0c09-4ea1-9419-36783b5fc8c5.png)

已修复：ea9ee34ca5891c44d2048e7c619ee46269107b76
