### ISSUE TITLE
新的报错和图片消息推送问题反馈

### ISSUE THREAD

**Issue by Ai-Yolo** [JustUndertaker/ntchat-client#3]
软件版本：0.3.1
问题描述：调用接口发送拍一拍或者图片 提示报错如下
![image](https://user-images.githubusercontent.com/11790369/198235830-a954e053-a25e-418f-b800-4d3fbe5f97df.png)

**Comment by Ai-Yolo** [comment]
问题描述：收到图片后 WS没推送消息事件，11047

**Comment by Ai-Yolo** [comment]
还有个奇怪的问题，应该是我这边的原因，我本地win11能正常调用接口发送本地图片，但是换到Windows Server 2019的服务器上，能调用成功接口，但是没有图片发出去，只有发本地图片有这个问题...

**Comment by JustUndertaker** [comment]
> 问题描述：收到图片后 WS没推送消息事件，11047

开启debug，现在收到图片会有一段时间解密延迟，所以推送消息会在解密图片后再推送。

**Comment by Ai-Yolo** [comment]
> > 问题描述：收到图片后 WS没推送消息事件，11047
> 
> 开启debug，现在收到图片会有一段时间解密延迟，所以推送消息会在解密图片后再推送。

![image](https://user-images.githubusercontent.com/11790369/198244300-4a18c056-590f-447d-9434-38f66f688e91.png)
大佬，确实没推送...我又测了一下http推送也还是没有...其他消息倒是正常

**Comment by JustUndertaker** [comment]
> > > 问题描述：收到图片后 WS没推送消息事件，11047
> > 
> > 
> > 开启debug，现在收到图片会有一段时间解密延迟，所以推送消息会在解密图片后再推送。
> 
> ![image](https://user-images.githubusercontent.com/11790369/198244300-4a18c056-590f-447d-9434-38f66f688e91.png) 大佬，确实没推送...我又测了一下http推送也还是没有...其他消息倒是正常

fixed in next version.
