### ISSUE TITLE
OPENSSL_Uplink(00007FF9BD08BD50,08): no OPENSSL_Applink

### ISSUE THREAD

**Issue by Tokeii0** [JustUndertaker/ntchat-client#4]
![image](https://user-images.githubusercontent.com/111427585/198505675-55b16ee3-d37b-4c23-86b9-489b2b3c1319.png)
直接运行弹出该报错

**Comment by JustUndertaker** [comment]
> ![image](https://user-images.githubusercontent.com/111427585/198505675-55b16ee3-d37b-4c23-86b9-489b2b3c1319.png) 直接运行弹出该报错

请确保你的微信版本为：[3.6.0.18]
同时，不建议直接双击运行程序，这样报错可能捕捉不到，建议使用cmd，或者windows terminal运行.

**Comment by Tokeii0** [comment]
> 请确保你的微信版本为：[3.6.0.18] 同时，不建议直接双击运行程序，这样报错可能捕捉不到，建议使用cmd，或者windows terminal运行.

我是用windows terminal运行 ，应该不是微信版本问题，我是安装的3.6.0.18版本的微信，而且我在服务器运行该程序是没有出现no OPENSSL_Applink报错

**Comment by JustUndertaker** [comment]
> > 请确保你的微信版本为：[3.6.0.18] 同时，不建议直接双击运行程序，这样报错可能捕捉不到，建议使用cmd，或者windows terminal运行.
> 
> 我是用windows terminal运行 ，应该不是微信版本问题，我是安装的3.6.0.18版本的微信，而且我在服务器运行该程序是没有出现no OPENSSL_Applink报错

可能是系统环境问题，这个问题应该和上游ntchat有关，我这边没法解决。

**Comment by Tokeii0** [comment]
新版本无 no OPENSSL_Applink报错
