### ISSUE TITLE
一直报错无法连接到websocket。有遇到的吗

### ISSUE THREAD

**Issue by wwk86** [JustUndertaker/ntchat-client#7]
一直报错无法连接到websocket。有遇到的吗

**Comment by JustUndertaker** [comment]
请描述清楚问题，并附带对应日志。
最好是配置也发出来

**Comment by wwk86** [comment]
[客户端1](http://rldj9kauo.hd-bkt.clouddn.com/%E5%AE%A2%E6%88%B7%E7%AB%AF1.png)
[客户端2](http://rldj9kauo.hd-bkt.clouddn.com/%E5%AE%A2%E6%88%B7%E7%AB%AF2.png)
[客户端3](http://rldj9kauo.hd-bkt.clouddn.com/%E5%AE%A2%E6%88%B7%E7%AB%AF3.png)
[服务端1](http://rldj9kauo.hd-bkt.clouddn.com/%E6%9C%8D%E5%8A%A1%E7%AB%AF1.png)
感谢作者无私奉献，谢谢

**Comment by JustUndertaker** [comment]
ws地址需要填写协议名称，比如：
ws://192.168.100.219:8080/ntchat/ws

**Comment by wwk86** [comment]
谢谢，客户端按照要求做了更改。
客户端提示：连接到ws地址发生错误：
11-15 14:31:50 [INFO] ntchat_client | websocket - 正在连接到：ws://192.168.100.219:8080/ntchat/ws
11-15 14:31:50 [ERROR] ntchat_client | websocket - 连接到ws地址发生错误：server rejected WebSocket connection: HTTP 403

服务端提示：
11-15 14:31:49 [INFO] uvicorn | ('192.168.100.66', 54933) - "WebSocket /ntchat/ws" 403
11-15 14:31:49 [INFO] websockets | connection failed (403 Forbidden)
11-15 14:31:49 [INFO] websockets | connection closed

**Comment by JustUndertaker** [comment]
nb2需要使用adapter-ntchat适配器并注册，在bot.py中
```python
from nonebot.adapters.ntchat import Adapter

driver = nonebot.get_driver()
driver.register_adapter(Adapter)
```

**Comment by wwk86** [comment]
完美解决了。谢谢

**Comment by zrwkkd** [comment]
> nb2需要使用adapter-ntchat适配器并注册，在bot.py中
> 
> ```python
> from nonebot.adapters.ntchat import Adapter
> 
> driver = nonebot.get_driver()
> driver.register_adapter(Adapter)
> ```
新手小白打搅了
我也遇到题主同样的问题，查看一下nonebot2的使用说明和这层回复，还是不太明白如何注册适配器

**Comment by Yuelioi** [comment]
给个示例文件参考(nb2)

```python
import nonebot

from nonebot.adapters.ntchat import TextMessageEvent
from nonebot.plugin import on
from nonebot.adapters.ntchat import Adapter

nonebot.init()
driver = nonebot.get_driver()
driver.register_adapter(Adapter)

matcher = on("app")  # rule,permission等参数同样可以加入

@matcher.handle()
async def _(event: TextMessageEvent):
    print(dir(event))

if __name__ == "__main__":
    nonebot.run()
```
