### ISSUE TITLE
连接不到我的nonebot

### ISSUE THREAD

**Issue by Annnnh1010** [JustUndertaker/ntchat-client#9]
![VeryCapture_20221214114508](https://user-images.githubusercontent.com/76246787/207500507-566dae81-91ef-4287-812a-13ae3223dfa2.jpg)

**Comment by JustUndertaker** [comment]
> 

看报错，需要将ws地址协议写上，ws://xxx，或者wss://xxxx

**Comment by Annnnh1010** [comment]
唔~找到原因了  我添加一下适配器就好了   但是我只能接受消息 不能像QQ一样发一个色图就会给我回复一张图片

**Comment by JustUndertaker** [comment]
> 

确认你的插件适合这个适配器哦。

**Comment by Annnnh1010** [comment]
适合适合 nonebot也收到别人给我微信发的消息了 但是不会回过去  nonebot装插件了的 QQ可以用

**Comment by JustUndertaker** [comment]
> 适合适合 nonebot也收到别人给我微信发的消息了 但是不会回过去 nonebot装插件了的 QQ可以用

那就是不适合，改改插件吧

**Comment by Annnnh1010** [comment]
啊这 好吧
